# Generated by Django 5.2.1 on 2025-06-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistereduser',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='preregistereduser',
            name='verified',
        ),
        migrations.AlterField(
            model_name='preregistereduser',
            name='eligibility',
            field=models.BooleanField(default=True),
        ),
    ]
