# Generated by Django 5.2.1 on 2025-06-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_alter_preregistereduser_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistereduser',
            name='eligibility',
            field=models.CharField(max_length=10),
        ),
    ]
